In [1]:
import torch

if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"CUDA device name: {torch.cuda.get_device_name()}")
else:
    print("CUDA is not available.")

CUDA device name: NVIDIA GeForce GTX 1650 Ti with Max-Q Design

In [2]:
import pandas as pd
from matplotlib import pyplot as plt

import pandas as pd
import re

# Read the CSV file into a DataFrame
tweet_data_int = pd.read_csv('train_nick.csv')
tweet_data_int.head()

# Convert 'tweet' column to string data type and remove non-string entries
tweet_data_int['tweet'] = tweet_data_int['tweet'].astype(str)
tweet_data_int = tweet_data_int[tweet_data_int['tweet'].apply(lambda x: isinstance(x, str))]

# Join the list of words into a single string
tweet_data_int['tweet'] = tweet_data_int['tweet'].apply(lambda x: ' '.join(x))

In [3]:
# sample 5% of data to be used as unseen data
data_int = tweet_data_int.sample(frac=0.95, random_state=786)

data_int_unseen = data_int.drop(data_int.index)
data_int.reset_index(inplace=True, drop=True)
data_int_unseen.reset_index(inplace=True, drop=True)

print(data_int_unseen)
# print the revised shape
print('Data for Modeling: ' + str(data_int.shape))
print('Unseen Data For Predictions: ' + str(data_int_unseen.shape))

Empty DataFrame
Columns: [company, sentiment, tweet]
Index: []
Data for Modeling: (70296, 3)
Unseen Data For Predictions: (0, 3)

In [4]:
# init setup
from pycaret.classification import *
s = setup(data = data_int, target = 'sentiment', session_id=123)
best_model = compare_models()

In [5]:
ridge_int= create_model('ridge')
svm_int= create_model('svm')
lda_int= create_model('lda')
dummy_int= create_model('dummy')
qda_int= create_model('qda')
lightgbm_int= create_model('lightgbm')
rf_int= create_model('rf')
dt_int= create_model('dt')
et_int= create_model('et')
gbc_int= create_model('gbc')
knn_int= create_model('knn')
nb_int= create_model('nb')
ada_int= create_model('ada')
lr_int= create_model('lr')

In [6]:
tuneridge_int = tune_model(ridge_int)
tunesvm_int = tune_model(svm_int)
tunelda_int = tune_model(lda_int)
tunedummy_int = tune_model(dummy_int)
tuneqda_int = tune_model(qda_int)
tunelightgbm_int = tune_model(lightgbm_int)
tunerf_int = tune_model(rf_int)
tunedt_int = tune_model(dt_int)
tuneet_int = tune_model(et_int)
tunegbc_int = tune_model(gbc_int)
tuneknn_int = tune_model(knn_int)
tunenb_int = tune_model(nb_int)
tuneada_int = tune_model(ada_int)
tunelr_int = tune_model(lr_int)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 4 candidates, totalling 40 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Fitting 10 folds for each of 10 candidates, totalling 100 fits